name: Style Check

on: 
  pull_request:
    branches: [ main ]

jobs:
  style-and-lint-check:
    name: Style and Lint Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install
    
    - name: Run build check
      run: |
        npm run build
        if [ $? -ne 0 ]; then
          echo "Code failed to build. Please fix the issues before merging."
          exit 1
        fi

    - name: Run style check
      run: |
        npm run style
        if [ $? -ne 0 ]; then
          echo "Code style check failed. Please fix the issues before merging."
          exit 1
        fi

    - name: Run lint check
      run: |
        npm run lint
        if [ $? -ne 0 ]; then
          echo "Lint check failed. Please fix the issues before merging."
          exit 1
        fi