name: Style Check

on: 
  pull_request:
    branches: [ main ]  # Replace 'main' with your default branch name

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Use the appropriate Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run style check
      run: npm run style

    - name: Check for status
      run: |
        if [ $? -ne 0 ]; then
          echo "Code style check failed. Please fix the issues before merging."
          exit 1
        fi
